
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 06 11:51:12 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 44;
  public static final int CONST = 23;
  public static final int GRTEQ = 36;
  public static final int GRT = 35;
  public static final int REM = 18;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 27;
  public static final int CMPEQUAL = 33;
  public static final int LESS = 37;
  public static final int MINUS = 15;
  public static final int RPAREN = 7;
  public static final int FINDREPLACE = 40;
  public static final int AND = 32;
  public static final int OR = 31;
  public static final int BOOL = 41;
  public static final int COMMA = 8;
  public static final int INC = 21;
  public static final int DIV = 17;
  public static final int PLUS = 12;
  public static final int IF = 45;
  public static final int LESSEQ = 38;
  public static final int DOT = 29;
  public static final int FINDANY = 30;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int EQUAL = 9;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int MUL = 16;
  public static final int NUMBER = 42;
  public static final int IDENT = 43;
  public static final int BREAK = 26;
  public static final int VOID = 13;
  public static final int FORARROW = 39;
  public static final int FOREACH = 25;
  public static final int ELSE = 46;
  public static final int LBRACE = 3;
  public static final int LSQUARE = 19;
  public static final int READ = 14;
  public static final int RSQUARE = 20;
  public static final int WHILE = 24;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int DIFF = 34;
  public static final int DEC = 22;
  public static final int PRINT = 10;
}

